import { useState, useEffect } from 'react';
import { getDatabase, ref, onValue } from 'firebase/database';
import firebase from './firebase';

// Save game button:
// - What does it record?
// 1) The number of correct and wrong choices - counters.
// 2) The array of question generated by the API.
// 3) The index of the question being played at the moment of saving.
// - How does it store it?
// 1) In an array.
// 2) In an array of object (???)

const SaveGame = ()=>{
    
    useEffect(()=>{
        
        const database = getDatabase(firebase);
        const dbRef = ref(database);

        onValue(dbRef, (response)=>{

            const newState = []
            const data = response.val()
            for(let key in data){
                newState.push({
                    id:key, 
                    name:data[key]
                })
            }

        })
    })

    return (
        <>
    
        </>

    );
}

export default SaveGame;