// Modules
import { useState, useEffect } from 'react';
import { getDatabase, ref, onValue } from 'firebase/database';
// Config
import firebase from './firebase';
import axios from 'axios';
// Components
import SaveGame from './Components/SaveGame'; 

// Styling
import './App.css';

// Save game button:
// - What does it record?
// 1) The number of correct and wrong choices - counters.
// 2) The array of question generated by the API.
// 3) The index of the question being played at the moment of saving.
// Display saved game button:
// - How does it store it?
// 1) In an array.
// 2) In an array of object (???)
// Load game button:
// - How does it display the saves?
// 1) Make a component to display all the saves visually.
// - How does it load the save?
// 1) Assign the selected saves to the display game component.

function App() {
  
  const [ score, setScore ] = useState('');
  const [ currentQuestion, setCurrentQuestion ] = useState('');
  const [ questionList, setQuestionList ] = useState('');

  return (
    <div className="App">
      <h1>Quarantine Pursuit Project</h1>

      <SaveGame />
    </div>
  );
}

export default App;
