
// Modules
import { useEffect, useState } from "react";
// Config
// import axios from 'axios';

// Components
import SaveGame from './Components/SaveGame'; 
import LoadGame from './Components/LoadGame';

// Styling
import "./App.css";
import axios from "axios";
import Dropdown from "./Components/Dropdown";
import ClearPageButton from "./Components/ClearPageButton";
import QuizCall from "./Components/QuizCall";


// Save game button:
// - What does it record?
// 1) The number of correct and wrong choices - counters.
// 2) The array of question generated by the API.
// 3) The index of the question being played at the moment of saving.
// Display saved game button:
// - How does it store it?
// 1) In an array.
// 2) In an array of object (???)
// Load game button:
// - How does it display the saves?
// 1) Make a component to display all the saves visually.
// - How does it load the save?
// 1) Assign the selected saves to the display game component.

function App() {

  
  const [ score, setScore ] = useState(['']);
  const [ currentQuestion, setCurrentQuestion ] = useState('');
  const [ questionList, setQuestionList ] = useState([]);

  const testFunction = ()=>{
    return (
      setScore('5'),
      setCurrentQuestion('6'),
      setQuestionList([
        {
          numberOfQuestion: "10",
          numberOfRightAnswer: "1"},
        {
          numberOfQuestion: "5",
          numberOfRightAnswer: "1"}    
      ])
    )
  }


  return (
    <div className="App">
      <h1>Quarantine Pursuit Project</h1>
      <Dropdown />
      <ClearPageButton />
      <QuizCall />
      <div className='saveGame'>
        {/* Communicate with firebase in this component */}
        <SaveGame 
        score = { score }
        setScore = { setScore }
        currentQuestion = { currentQuestion }
        setCurrentQuestion = { setCurrentQuestion }
        questionList = { questionList }
        setQuestionList = { setQuestionList }
        testFunction = { testFunction }
        />
      </div>
      <div className="loadGame">
        <LoadGame />
      </div>
  );
}

export default App;
